version: "3"
services:
  app:
    build: .
    container_name: "back"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
      - "8004:8004"
    volumes:
      - .:/app
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
  postgres:
    image: postgres:11.2-alpine
    container_name: "psql"
    ports:
      - "5432:5432"
      - "8080:8080"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: localhost
    volumes:
        - '/var/lib/postgresql/data:/var/lib/postgresql/data'